apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "order-otus.fullname" . }}-migration"
spec:
  template:
    spec:
      containers:
      - name: migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["alembic",  "upgrade", "head"]
        env:
          - name: PG__HOST
            value: {{ .Values.postgresql.host }}
          - name: PG__USER
            value: {{ .Values.postgresql.auth.username }}
          - name: PG__DB
            value: {{ .Values.postgresql.auth.database }}
          - name: PG__PASSWORD
            value: {{ .Values.postgresql.auth.password }}
      restartPolicy: OnFailure
  backoffLimit: 4