"""'initial'

Revision ID: 407249cb3d27
Revises: c852702ccb67
Create Date: 2023-12-10 19:33:56.515384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407249cb3d27'
down_revision: Union[str, None] = 'c852702ccb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
